# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_facttabledemo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FactTableDemo',
        ),
    ]
