# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_facttabledemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_no', models.CharField(blank=True, max_length=300, null=True)),
                ('first_free_join_date', models.DateTimeField(blank=True, null=True)),
                ('last_free_subscription_date', models.DateTimeField(blank=True, null=True)),
                ('first_piad_subscription_date', models.DateTimeField(blank=True, null=True)),
                ('last_piad_subscription_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_renew_performed', models.IntegerField(blank=True, null=True)),
                ('number_of_paid_subscription', models.IntegerField(blank=True, null=True)),
                ('first_retailer_or_channel', models.CharField(blank=True, max_length=300, null=True)),
                ('avg_membership_duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
