# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='avg_membership_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
